name: Upload to Azure Blob
 
on:
  push:
    paths:
      - web/**
      
  workflow_dispatch:
      
env:
  RESOURCE_GROUP: 'RG-Connectivity'
  STORAGE_ACCOUNT: 'stopasswordgenrvdwegen'
  CDN_PROFILE: 'sto-vdwegen-cdn'
  CDN_ENDPOINT: 'stopasswordgenrvdwegen'

jobs:
  check_run:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - run: echo "${{ github.event.head_commit.message }}"

  build:
    runs-on: ubuntu-latest
    needs: check_run
    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
         inlineScript: |
            az storage blob upload-batch --overwrite true --account-name $STORAGE_ACCOUNT --auth-mode key -d '$web' -s web
      - name: Purge CDN endpoint
        uses: azure/CLI@v1
        with:
         inlineScript: |
           az cdn endpoint purge --content-paths  "/*" --profile-name $CDN_PROFILE --name $CDN_ENDPOINT --resource-group $RESOURCE_GROUP
      - name: logout
        run: |
            az logout
